<a href="https://colab.research.google.com/github/susantagorai8903-lgtm/Birthday-wish/blob/main/Day2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
brics = pd.read_csv("brics.csv")
brics

  Unnamed: 0       country  population      area    capital
0         BR        Brazil         200   8515767   Brasilia
1         RU        Russia         144  17098242     Moscow
2         IN         India        1252   3287590  New Delhi
3         CH         China        1357   9596961    Beijing
4         SA  South Africa          55   1221037   Pretoria

In [ ]:
brics = pd.read_csv("brics.csv", index_col = 0)
brics

         country  population      area    capital
BR        Brazil         200   8515767   Brasilia
RU        Russia         144  17098242     Moscow
IN         India        1252   3287590  New Delhi
CH         China        1357   9596961    Beijing
SA  South Africa          55   1221037   Pretoria

In [ ]:
brics.describe()

        population          area
count     5.000000  5.000000e+00
mean    601.600000  7.943919e+06
std     644.806405  6.199591e+06
min      55.000000  1.221037e+06
25%     144.000000  3.287590e+06
50%     200.000000  8.515767e+06
75%    1252.000000  9.596961e+06
max    1357.000000  1.709824e+07

In [ ]:
brics["country"]  # extracting data

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [ ]:
brics.country

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [ ]:
brics["density"] = brics["population"] / brics["area"]
brics

         country  population      area    capital   density
BR        Brazil         200   8515767   Brasilia  0.000023
RU        Russia         144  17098242     Moscow  0.000008
IN         India        1252   3287590  New Delhi  0.000381
CH         China        1357   9596961    Beijing  0.000141
SA  South Africa          55   1221037   Pretoria  0.000045

In [ ]:
print(brics[brics["population"] > 350]["country"])

IN    India
CH    China
Name: country, dtype: object

In [ ]:
df.nlargest(3, 'population')['country']
for country in top3:
    print(country)

China
India
Brazil

In [ ]:
brics.sort_values(by='population', ascending=False).head(3)['country']

CH     China
IN     India
BR    Brazil
Name: country, dtype: object

In [ ]:
brics.iloc[1:3, 2:4]

        area    capital
RU  17098242     Moscow
IN   3287590  New Delhi

In [ ]:
brics.iloc[1:3]

   country  population      area    capital   density
RU  Russia         144  17098242     Moscow  0.000008
IN   India        1252   3287590  New Delhi  0.000381

In [ ]:
import pandas as pd
census = pd.read_csv("census.csv")
census

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
1,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
2,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
3,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
4,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3138,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3139,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3140,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3141,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [ ]:
census = pd.read_csv("census.csv", index_col = 0)
census

,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
SUMLEV,,,,,,,,,,,,,,,,,,,,,
50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,55253,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,186659,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,27226,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,22733,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
50,3,6,1,9,Alabama,Blount County,57322,57322,57373,57711,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,44041,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,21482,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,20912,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,8469,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,7114,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [ ]:
census.groupby("STNAME")["CTYNAME"].count().idxmax()

'Texas'

In [ ]:
census.groupby("STNAME") \
      .apply(lambda x: x.nlargest(3, "CENSUS2010POP")["CENSUS2010POP"].sum()) \
      .nlargest(3)

/tmp/ipython-input-1711142462.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.nlargest(3, "CENSUS2010POP")["CENSUS2010POP"].sum()) \

STNAME
California    15924150
Texas          8269632
Illinois       6815061
dtype: int64

In [ ]:
x = census.groupby('STNAME').size()
ans = x.idxmax()
print(ans)

Texas

In [ ]:
top_contries_df = census.df.sort_values(by=['STNAME', 'CENSUS2010POP'], ascending=False).groupby('STNAME').head(3)
ans = top_contries_df.groupby('STNAME').sum().sort_values(by='CENSUS2010POP', ascending=False).head(3).index.tolist()
print(ans)

NameError: name 'census' is not defined

In [ ]:
top_counties_df = census.sort_values(by=['STNAME',"CENSUS2010POP"],
                                         ascending=False).groupby('STNAME').head(3)
ans = top_counties_df.groupby('STNAME').sum().sort_values(by='CENSUS2010POP',
                                                          ascending=False).head(3).index.tolist()
print(ans)

NameError: name 'census' is not defined

In [ ]:
top_counties_df = census.sort_values(by=['STNAME',"CENSUS2010POP"], ascending=False).groupby('STNAME').head(3)
ans = top_counties_df.groupby('STNAME').sum().sort_values(by='CENSUS2010POP', ascending=False).head(3).index.tolist()
print(ans)

NameError: name 'census' is not defined

In [ ]:
data